version: '3'

services:
  redis:
    image: docker.io/library/redis:alpine
    environment:
      - DOMAIN_NAME=redis.${BASEHOST:-magento.docker}

  mysql:
    image: docker.io/library/mysql:${MYSQLVERSION:-8}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-toor}
      - DOMAIN_NAME=mysql.${BASEHOST:-magento.docker}
    command: --innodb-doublewrite=0

  mailcatcher:
    image: docker.io/mailhog/mailhog:latest
    environment:
      - VIRTUAL_HOST=mailcatcher.${BASEHOST:-magento.docker}

  application:
    image: docker.io/dockerwest/php-magento${MAGENTOVERSION}:${PHPVERSION:-7.0}
    environment:
      - C_UID=${C_UID:-1000}
      - C_GID=${C_GID:-1000}
      - DEVELOPMENT=${DEVELOPMENT:-1}
    volumes:
      - ${APPLICATION:-../magento}:/phpapp

  nginx:
    image: docker.io/dockerwest/nginx-magento${MAGENTOVERSION}:${NGINXVERSION:-stable}
    environment:
      - VIRTUAL_HOST=${BASEHOST:-magento.docker},${EXTRAHOSTS}
    volumes:
      - ${APPLICATION:-../magento}:/phpapp

  elastic:
    image: docker.io/blacktop/elasticsearch:${ELASTICSEARCHVERSION:-7}
    environment:
      - DOMAIN_NAME=elastic.${BASEHOST:-magento.docker}

  elastic-hq:
    image: docker.io/elastichq/elasticsearch-hq
    environment:
      - VIRTUAL_HOST=hq.${BASEHOST:-magento.docker}

